// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Admin View Unapproved Events', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Admin View Unapproved Events', async function() {
    // Test name: Admin View Unapproved Events
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1552x832 | 
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    // 3 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 4 | type | id=email | hanyelbob99@gmail.com
    await driver.findElement(By.id("email")).sendKeys("hanyelbob99@gmail.com")
    // 5 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 6 | type | id=password | capstone123
    await driver.findElement(By.id("password")).sendKeys("capstone123")
    // 7 | click | id=btn | 
    await driver.findElement(By.id("btn")).click()
    // 8 | click | css=.status-btn:nth-child(2) | 
    await driver.findElement(By.css(".status-btn:nth-child(2)")).click()
    // 9 | click | id=eventImage | 
    await driver.findElement(By.id("eventImage")).click()
    // 10 | assertElementPresent | css=.logout-btn:nth-child(1) | 
    {
      const elements = await driver.findElements(By.css(".logout-btn:nth-child(1)"))
      assert(elements.length)
    }
    // 11 | assertElementPresent | css=.reject-btn | 
    {
      const elements = await driver.findElements(By.css(".reject-btn"))
      assert(elements.length)
    }
  })
})
