// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Admin Reject/View Rejected Events', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Admin Reject/View Rejected Events', async function() {
    // Test name: Admin Reject/View Rejected Events
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 3 | type | id=email | hanyelbob99@gmail.com
    await driver.findElement(By.id("email")).sendKeys("hanyelbob99@gmail.com")
    // 4 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 5 | type | id=password | capstone123
    await driver.findElement(By.id("password")).sendKeys("capstone123")
    // 6 | click | css=html | 
    await driver.findElement(By.css("html")).click()
    // 7 | click | id=btn | 
    await driver.findElement(By.id("btn")).click()
    // 8 | click | css=.status-btn:nth-child(2) | 
    await driver.findElement(By.css(".status-btn:nth-child(2)")).click()
    // 9 | click | css=.event-banner:nth-child(1) .time-place | 
    await driver.findElement(By.css(".event-banner:nth-child(1) .time-place")).click()
    // 10 | click | css=.reject-btn | 
    await driver.findElement(By.css(".reject-btn")).click()
    // 11 | click | css=.comment-reject-btn | 
    await driver.findElement(By.css(".comment-reject-btn")).click()
    // 12 | pause | 3000 | 
    await driver.sleep(3000)
    // 13 | open | http://localhost:3000/dashboard | 
    await driver.get("http://localhost:3000/dashboard")
    // 14 | pause | 3000 | 
    await driver.sleep(3000)
    // 15 | click | css=.status-btn:nth-child(3) | 
    await driver.findElement(By.css(".status-btn:nth-child(3)")).click()
    // 16 | click | css=.event-banner:nth-child(2) .time-place | 
    await driver.findElement(By.css(".event-banner:nth-child(2) .time-place")).click()
    // 17 | assertElementPresent | css=.main-detail-left > .text:nth-child(1) > .text-content | Test Event
    {
      const elements = await driver.findElements(By.css(".main-detail-left > .text:nth-child(1) > .text-content"))
      assert(elements.length)
    }
  })
})
